import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import PageHero from "@/components/PageHero";
import Reveal from "@/components/Reveal";
import GlowButton from "@/components/GlowButton";

export const metadata: Metadata = {
  title: "Industrial Pumps and Dosing UAE | Pump Selection Guide | SensCore",
  description: "Technical guidance on industrial pumps, AODD pumps, metering and dosing pumps, centrifugal pumps and specialised pumping applications across the UAE.",
  alternates: { canonical: "https://www.senscoretech.com/knowledge-centre/pumps-dosing" },
};

const selectionPoints = ["Fluid and required flow rate", "Suction pressure and discharge pressure", "Temperature and viscosity", "Density and solids content", "Maximum particle size", "Chemical compatibility", "Construction material", "Connection size", "Operating frequency", "Available utilities", "Continuous or intermittent duty", "Dosing rate, accuracy and control philosophy where applicable"];
const faqs = [
  ["Which type of industrial pump should I select?", "The correct pump depends on the fluid, required flow, pressure, viscosity, solids content, temperature, suction conditions and operating pattern. Different applications may require AODD, centrifugal, metering or specialised pump technologies."],
  ["What is an AODD pump used for?", "AODD pumps are commonly used for chemical transfer, slurry, wastewater, viscous fluids and other industrial duties where air operated diaphragm pumping is suitable."],
  ["What is the difference between a metering pump and a normal transfer pump?", "A transfer pump primarily moves fluid between locations. A metering pump is designed to deliver a controlled quantity of fluid into a process."],
  ["Which pump is suitable for slurry or solids containing fluids?", "The answer depends on the solid’s concentration, particle size, viscosity and required flow. Specialised diaphragm pumps and other solids handling pump designs may be considered where conventional pumps are unsuitable."],
  ["What information is required to select an industrial pump?", "Useful information includes the fluid, flow rate, suction conditions, discharge pressure, temperature, viscosity, solids content, required materials, connection size and operating duty."],
];

const sections = [
  ["AODD Pumps", ["Air Operated Double Diaphragm pumps use compressed air to move flexible diaphragms and transfer fluid through alternating pumping chambers.", "AODD pumps are widely used where the process involves chemicals, viscous liquids, slurry, wastewater, suspended solids or fluids that require careful material selection.", "Metallic and non-metallic constructions allow the pump materials to be matched to different process conditions.", "Typical selection considerations include fluid compatibility, required capacity, discharge pressure, suction conditions, solids size, diaphragm material and available compressed air supply.", "AODD pumps can also be useful where variable flow, dry running capability or portable operation is required, provided the specific pump design is suitable for the duty."]],
  ["Metering and Dosing Pumps", ["Metering pumps are designed for controlled delivery of liquids into a process.", "They are commonly used for chemical dosing, water treatment, disinfection, pH correction, process additives and other applications where repeatable fluid injection is required.", "The required dosing rate, discharge pressure, chemical properties and control method should be defined before selecting the pump.", "Depending on the application, dosing systems may use technologies such as diaphragm, plunger, hydraulic diaphragm or solenoid driven pumps.", "Accuracy should always be considered together with suction conditions, chemical compatibility, installation and actual operating pressure."]],
  ["Specialised Pumps", ["Some fluids cannot be handled effectively by a conventional general-purpose pump.", "Powders, slurry, viscous materials, food products, abrasive media and fluids containing larger solids can require specialised pump designs.", "Application specific diaphragm pumps can be configured for duties where solids handling, sanitary construction, gentle product transfer or resistance to abrasion is important.", "The internal flow path, valve arrangement, diaphragm material and wetted components should all be evaluated against the actual process.", "This is particularly important for slurry and solids containing services, where incorrect pump selection can lead to blockage, excessive wear or unreliable operation."]],
  ["Centrifugal and Process Pumps", ["Centrifugal pumps are widely used for transferring liquids through industrial systems.", "They generate flow by transferring rotational energy from an impeller to the liquid and are commonly used for water circulation, utilities, cooling systems, process transfer and general industrial pumping.", "Typical configurations can include end suction pumps, multistage pumps, vertical inline pumps and engineered process pump arrangements.", "Selection should consider the required duty point, suction conditions, system resistance, fluid properties, material compatibility and expected operating range.", "Selecting a pump only around the maximum required flow can result in inefficient operation. The relationship between the pump curve and the actual system curve should be considered so that the pump operates within a suitable region of its performance range."]],
  ["Pump Materials and Fluid Compatibility", ["Pump materials should be selected around the process fluid rather than around the application name alone.", "Important factors can include chemical concentration, temperature, corrosion, abrasion, solids content and hygiene requirements.", "Metallic construction may be suitable for many industrial duties, while engineered plastics and other non-metallic materials may be preferable for certain corrosive chemicals.", "Elastomers, diaphragms, valve seats and seals must also be checked because compatibility of the pump body alone does not guarantee compatibility of the complete pump."]],
  ["Pump Spares and Accessories", ["Pump reliability depends on both the original selection and continued maintenance.", "Common replacement components can include diaphragms, valve balls, valve seats, air valve assemblies, seals and repair kits.", "Accessories such as pulsation dampeners and air regulators can also form part of the pumping arrangement.", "Maintenance requirements should therefore be considered during pump selection, particularly for continuously operated equipment or critical process duties.", "Availability of suitable spare parts can also influence the long-term operating value of the pump."]],
  ["Typical Industrial Pump Applications", ["Industrial pumps are used across water and wastewater treatment, chemical processing, oil and gas, manufacturing, food and beverage, utilities, building services and general process industries.", "Typical applications include chemical transfer, tank transfer, drum unloading, slurry handling, wastewater pumping, water circulation, chemical dosing, process additive injection, cooling water and general process fluid transfer."]],
  ["Industrial Pump Support Across the UAE", ["SensCore supports industrial pump and dosing requirements across Abu Dhabi, Dubai, Sharjah, Ajman, Ras Al Khaimah (RAK), Fujairah and Umm Al Quwain (UAQ).", "Our selection approach considers the required duty point, fluid characteristics, operating conditions, material compatibility and lifecycle requirements rather than simply the initial pump cost.", "Support is available for new projects, replacement requirements, plant upgrades and industrial maintenance applications throughout the UAE."]],
] as const;

export default function PumpsDosingPage() {
  return (
    <>
      <PageHero eyebrow="Knowledge Centre" title="Industrial Pumps and Dosing" description="Technical guidance on industrial pumps, AODD pumps, metering and dosing pumps, centrifugal pumps and specialised pumping applications across the UAE." />
      <main className="py-20 sm:py-28"><div className="mx-auto max-w-5xl px-6 lg:px-10">
        <Reveal><Link href="/knowledge-centre" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.18em] text-teal hover:text-ink"><ArrowLeft size={14} /> Back to Knowledge Centre</Link></Reveal>
        <div className="mt-10 space-y-7">
          <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Industrial Pumps and Dosing</h2><div className="mt-5 space-y-4 text-sm leading-8 text-mute"><p>Industrial pump selection starts with the application.</p><p>Flow rate and pressure are important, but they are only part of the selection process. Fluid properties, viscosity, solids content, chemical compatibility, suction conditions, temperature, operating pattern and maintenance requirements can all influence which pump technology is suitable.</p><p>SensCore supports industrial pumping applications ranging from fluid transfer and chemical dosing to slurry handling, process circulation and specialised pumping duties.</p></div></section></Reveal>
          {sections.map(([title, paragraphs]) => <Reveal key={title}><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">{title}</h2><div className="mt-5 space-y-4 text-sm leading-8 text-mute">{paragraphs.map((p) => <p key={p}>{p}</p>)}</div></section></Reveal>)}
          <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">What Should Engineers Consider When Selecting an Industrial Pump?</h2><p className="mt-5 text-sm leading-8 text-mute">The starting point should be the required duty. Important information includes:</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{selectionPoints.map((item) => <div key={item} className="flex items-start gap-2 rounded-xl border border-line bg-void/30 p-4 text-sm text-mute"><CheckCircle2 className="mt-0.5 shrink-0 text-teal" size={17} />{item}</div>)}</div><p className="mt-7 text-sm leading-8 text-mute">The lowest initial purchase cost does not necessarily represent the most suitable pumping solution if operating efficiency, maintenance requirements and service life are considered.</p></section></Reveal>
          <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Frequently Asked Questions</h2><div className="mt-6 space-y-4">{faqs.map(([question, answer], index) => <div key={question} className="rounded-xl border border-line bg-void/30 p-5"><div className="flex items-start gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-teal/30 bg-teal/10 font-mono text-[10px] font-semibold text-teal">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-display text-base font-semibold leading-7 text-ink">{question}</h3><p className="mt-2 text-sm leading-7 text-mute">{answer}</p></div></div></div>)}</div></section></Reveal>
          <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Need Help with an Industrial Pump Application?</h2><p className="mt-5 text-sm leading-8 text-mute">SensCore can review your fluid properties, required duty point and operating conditions to help identify a suitable pump technology and configuration for industrial applications across the UAE.</p><div className="mt-7 flex flex-col gap-4 sm:flex-row"><GlowButton href="/contact">Request Pump Support</GlowButton><Link href="/knowledge-centre" className="inline-flex items-center justify-center gap-2 rounded-full border border-line px-6 py-3 text-sm font-medium text-ink transition hover:border-teal/50 hover:text-teal">More Knowledge Centre <ArrowRight size={16} /></Link></div></section></Reveal>
        </div>
      </div></main>
    </>
  );
}
