import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import PageHero from "@/components/PageHero";
import Reveal from "@/components/Reveal";
import GlowButton from "@/components/GlowButton";

export const metadata: Metadata = {
  title: "Valves and Flow Control UAE | Industrial Valves | SensCore",
  description: "Technical guidance on industrial valves, flow control, butterfly valves, ball valves, control valves and valve automation for applications across the UAE.",
  alternates: { canonical: "https://www.senscoretech.com/knowledge-centre/valves-flow-control" },
};

const selectionPoints = ["Required valve function: isolation, regulation, directional control or reverse-flow prevention", "Process medium", "Pipe size", "Pressure and temperature", "Flow requirement", "Material compatibility", "Solids content", "Corrosion and abrasion", "Connection standard", "Allowable pressure drop", "Required sealing performance", "Operating frequency", "Manual or automated actuation"];
const faqs = [
  ["Which valve is best for industrial isolation?", "There is no single valve suitable for every isolation duty. Ball, butterfly, gate and other valve types may be appropriate depending on pipe size, pressure, temperature, medium and required shut off performance."],
  ["What is the difference between a ball valve and a butterfly valve?", "A ball valve controls flow using a rotating ball, while a butterfly valve uses a rotating disc. The better choice depends on the application, size, pressure conditions, required flow characteristics and installation constraints."],
  ["When is a control valve required?", "A control valve is required when the process needs continuous regulation of variables such as flow, pressure, temperature or level rather than simple isolation."],
  ["Can industrial valves be automated?", "Yes. Suitable valves can be operated using pneumatic or electric actuators and can incorporate positioners, limit switches, solenoid valves and position indication."],
  ["What information is required to select an industrial valve?", "Key information includes the process medium, pipe size, pressure, temperature, flow requirement, valve function, connection standard, material requirement and whether manual or automated operation is required."],
];

const sections = [
  ["Butterfly Valves", ["Butterfly valves use a rotating disc to control or isolate flow and are widely used where compact installation and efficient operation are required.", "Common configurations include wafer, lug and double flanged designs. Depending on the application, concentric, high performance and triple offset arrangements may be considered.", "ABC Valve currently provides butterfly valve technologies for water treatment, industrial processes, slurry, abrasive service, air, steam and specialised applications. Certain ranges are available for large pipeline sizes and automated operation.", "Selection should consider pressure, temperature, valve size, seat material, disc material, required shut off performance and compatibility with the process medium."]],
  ["Ball Valves", ["Ball valves use a rotating ball with an internal flow passage to provide isolation or flow direction control.", "They are commonly selected where reliable shut off and relatively low flow resistance are required.", "Available configurations can include threaded, flanged, three-piece, three-way, floating and trunnion mounted designs. ABC Valve also offers lined ball valves for corrosive process applications and specialised ball valve configurations for industrial duties.", "Body material, seat material, pressure rating, connection type and required operating torque should be matched to the service conditions."]],
  ["Gate, Globe and Check Valves", ["Different valve designs perform different functions within a process system.", "Gate valves are primarily used for isolation where a relatively unrestricted flow path is required when fully open.", "Globe valves are commonly considered where flow regulation or throttling is required.", "Check valves allow flow in one direction while helping prevent reverse flow. They are frequently used around pumps and process systems where backflow should be controlled.", "SensCore supports these valve types within its wider industrial valve portfolio. ABC Valve also manufactures check valve and globe valve ranges for industrial applications."]],
  ["Specialised Valves for Challenging Applications", ["Standard valve designs may not be suitable for every process.", "Abrasive slurry, powders, corrosive chemicals and dry bulk materials can create specific challenges involving wear, material build up, sealing and operating torque.", "ABC Valve currently offers abrasion resistant butterfly valves, lined ball valves, inflatable seat butterfly valves, dome type valves, powder discharge valves, rotary valves and slide gate solutions for specialised fluid and material handling duties.", "The valve should therefore be selected around the behaviour of the process medium rather than simply its nominal pipeline size."]],
  ["Valve Actuation and Automation", ["Industrial valves can be operated manually or automatically depending on the process requirement.", "Pneumatic actuators are widely used where compressed air is available and rapid or frequent valve operation is required. Electric actuators provide another option where electrical operation or remote control is preferred.", "Automated valve assemblies may also include solenoid valves, limit switches, valve indicators and positioners.", "ABC Valve provides pneumatic actuators, valve positioners, solenoid valves, limit switches and valve indication devices for automated valve systems."]],
  ["Control Valves and Flow Regulation", ["Isolation and flow regulation are different engineering requirements.", "Where a valve must continuously regulate process conditions rather than simply open or close, the valve characteristics, actuator and control arrangement become particularly important.", "Control valve selection should consider the required flow capacity, pressure conditions, available pressure drop, fluid properties, operating range, actuator requirements and control signal.", "The final valve assembly should be evaluated as part of the complete process control loop."]],
  ["Typical Industrial Valve Applications", ["Industrial valves are used throughout water and wastewater treatment, oil and gas, chemical processing, petrochemical facilities, power generation, manufacturing, food and beverage, utilities, HVAC and industrial infrastructure.", "Typical duties include pipeline isolation, pump isolation, tank connections, chemical transfer, water distribution, cooling systems, steam service, process regulation, slurry handling, compressed air and automated process control.", "ABC Valve specifically provides solutions for sectors including chemical processing, water treatment, energy, semiconductor production, metallurgy, mining, marine and offshore applications."]],
  ["Industrial Valve Support Across the UAE", ["SensCore supports industrial valve and flow control requirements across Abu Dhabi, Dubai, Sharjah, Ajman, Ras Al Khaimah (RAK), Fujairah and Umm Al Quwain (UAQ).", "Our application-based approach considers the medium, process conditions, valve function, materials, actuation and control requirements before identifying a suitable valve configuration.", "Support is available for new projects, plant upgrades, maintenance requirements and replacement applications throughout the UAE."]],
] as const;

export default function ValvesFlowControlPage() {
  return (
    <>
      <PageHero eyebrow="Knowledge Centre" title="Industrial Valves and Flow Control" description="Technical guidance on industrial valves, flow control, butterfly valves, ball valves, control valves and valve automation for applications across the UAE." />
      <main className="py-20 sm:py-28"><div className="mx-auto max-w-5xl px-6 lg:px-10">
        <Reveal><Link href="/knowledge-centre" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.18em] text-teal hover:text-ink"><ArrowLeft size={14} /> Back to Knowledge Centre</Link></Reveal>
        <div className="mt-10 space-y-7">
          <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Industrial Valves and Flow Control</h2><div className="mt-5 space-y-4 text-sm leading-8 text-mute"><p>Industrial valves control, isolate, regulate or direct the movement of liquids, gases, steam, slurry and other process media.</p><p>Selecting the correct valve requires more than matching the pipeline size. Engineers must consider the fluid, pressure, temperature, flow characteristics, required function, materials, sealing arrangement, actuation method and operating environment.</p><p>SensCore supports industrial valve and flow control requirements for process plants, utilities, water systems, chemical applications and general industrial services across the UAE.</p></div></section></Reveal>
          {sections.map(([title, paragraphs]) => <Reveal key={title}><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">{title}</h2><div className="mt-5 space-y-4 text-sm leading-8 text-mute">{paragraphs.map((p) => <p key={p}>{p}</p>)}</div></section></Reveal>)}
          <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">What Should Engineers Consider When Selecting an Industrial Valve?</h2><p className="mt-5 text-sm leading-8 text-mute">Valve selection should begin with the required function. The engineer should define whether the valve is required for isolation, regulation, directional control, reverse flow prevention or automated operation.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{selectionPoints.map((item) => <div key={item} className="flex items-start gap-2 rounded-xl border border-line bg-void/30 p-4 text-sm text-mute"><CheckCircle2 className="mt-0.5 shrink-0 text-teal" size={17} />{item}</div>)}</div><p className="mt-7 text-sm leading-8 text-mute">Correct valve sizing and material selection are particularly important in demanding process applications.</p></section></Reveal>
          <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Frequently Asked Questions</h2><div className="mt-6 space-y-4">{faqs.map(([question, answer], index) => <div key={question} className="rounded-xl border border-line bg-void/30 p-5"><div className="flex items-start gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-teal/30 bg-teal/10 font-mono text-[10px] font-semibold text-teal">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-display text-base font-semibold leading-7 text-ink">{question}</h3><p className="mt-2 text-sm leading-7 text-mute">{answer}</p></div></div></div>)}</div></section></Reveal>
          <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Need Help with a Valve or Flow Control Application?</h2><p className="mt-5 text-sm leading-8 text-mute">SensCore can review your process conditions, pipeline requirements and operating philosophy to help identify a suitable valve type, material, actuation method and flow control arrangement for industrial applications across the UAE.</p><div className="mt-7 flex flex-col gap-4 sm:flex-row"><GlowButton href="/contact">Request Valve Support</GlowButton><Link href="/knowledge-centre" className="inline-flex items-center justify-center gap-2 rounded-full border border-line px-6 py-3 text-sm font-medium text-ink transition hover:border-teal/50 hover:text-teal">More Knowledge Centre <ArrowRight size={16} /></Link></div></section></Reveal>
        </div>
      </div></main>
    </>
  );
}
