import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import PageHero from "@/components/PageHero";
import Reveal from "@/components/Reveal";
import GlowButton from "@/components/GlowButton";

export const metadata: Metadata = {
  title: "Industrial Engineering and Instrumentation UAE | SensCore",
  description: "Practical guidance on instrument selection, specification, installation, commissioning, verification and industrial applications across the UAE.",
  alternates: { canonical: "https://www.senscoretech.com/knowledge-centre/engineering-practice" },
};

const specificationPoints = ["Measured or handled medium", "Operating and design conditions", "Measurement or operating range", "Pipe or vessel dimensions", "Materials of construction", "Process connections", "Accuracy requirements", "Electrical and communication requirements", "Environmental conditions", "Hazardous area requirements where applicable", "Applicable project standards"];
const faqs = [
  ["What information should be provided when selecting an industrial instrument?", "The process medium, operating range, pressure, temperature, pipe or vessel size, required accuracy, connection, materials and signal requirements are useful starting points."],
  ["Why is application-based selection important?", "Two instruments designed to measure the same variable may use completely different principles. Process conditions determine which principle is suitable for the application."],
  ["Can an incorrect installation affect measurement accuracy?", "Yes. Instrument orientation, location, pipe conditions, vessel geometry, process connections and other installation factors can influence measurement performance."],
  ["What is checked during instrument commissioning?", "Commissioning can include installation inspection, configuration, signal testing, loop checking, communication verification and confirmation that the measurement is correctly received by the control system."],
  ["Should an instrument be replaced when the reading appears incorrect?", "Not necessarily. The process condition, installation, configuration, signal path and instrument condition should first be investigated to determine the actual source of the problem."],
];

const sections = [
  ["Application Based Instrument Selection", ["The same measurement requirement can often be solved using several technologies, but they may not perform equally well under the actual process conditions.", "Flowmeter selection, for example, may depend on conductivity, viscosity, solids content, pipe size, pressure, temperature and available installation space. Level measurement can be influenced by foam, vapour, dust, agitation and vessel geometry. Valve and pump selection introduces different considerations such as pressure loss, material compatibility, solids handling, operating frequency and required control function.", "The starting point should therefore be the application rather than a particular product or technology."]],
  ["Engineering Specification Review", ["A technical specification should define enough information for equipment to be selected correctly.", "Incomplete process information can result in technically compliant equipment that is still unsuitable for the actual application. Specification review should therefore consider both the written requirement and the intended operating condition."]],
  ["Instrument Installation", ["Correct instrument selection does not guarantee reliable measurement if the installation is unsuitable. Installation requirements vary significantly between technologies.", "Flowmeters may require particular pipe orientation, full pipe conditions or suitable upstream and downstream arrangements. Level instruments require correct positioning relative to vessel geometry and internal structures. Pressure instruments may require appropriate process connections and impulse arrangements. Temperature sensors require suitable insertion depth and thermal contact with the process.", "Installation should therefore be considered during instrument selection rather than after procurement."]],
  ["Commissioning and Loop Verification", ["Commissioning confirms that installed equipment operates as intended within the complete system.", "For instrumentation, this may include inspection of the installation, configuration review, signal testing, loop checking, communication verification and confirmation that the measured value reaches the intended control or monitoring system.", "The process is particularly important where instruments are integrated with PLC, HMI, SCADA or other automation platforms. A successful commissioning process should verify the measurement chain rather than looking only at the individual field instrument."]],
  ["Measurement Verification and Maintenance", ["Industrial instruments can require periodic inspection, verification or calibration depending on their function, operating conditions and plant requirements.", "A measurement that appears stable is not necessarily accurate. Verification can help determine whether an installed instrument is performing within the expected condition without automatically assuming that replacement is necessary.", "Maintenance planning should consider instrument criticality, operating environment, historical performance and the consequences of measurement error."]],
  ["Troubleshooting Industrial Measurement Problems", ["Unexpected readings do not always indicate instrument failure. Measurement problems can originate from the process, installation, configuration, wiring, communication, mechanical condition or the sensing technology itself.", "Effective troubleshooting should therefore begin by confirming the process conditions and installation before replacing equipment.", "Common questions include whether the pipe is full, whether the process medium has changed, whether a sensor is affected by build-up, whether valves are correctly positioned and whether the control system is receiving the expected signal.", "A structured approach can reduce unnecessary replacement and help identify the actual cause of the problem."]],
] as const;

const applications = [
  ["Water and Wastewater", "Applications can include flow measurement, tank level monitoring, pressure measurement, water quality analysis, valve control and chemical dosing."],
  ["Oil, Gas and Petrochemical", "Typical requirements can involve process measurement, flow control, pressure and temperature monitoring, hazardous fluid handling, flange protection and automation."],
  ["Chemical Processing", "Chemical compatibility becomes particularly important when selecting instruments, valves, pumps, gaskets and flange protection systems."],
  ["Manufacturing", "Manufacturing facilities can require compressed air monitoring, utility measurement, process automation, machine connectivity, fluid transfer and energy analysis."],
  ["Food and Beverage", "Applications can include water measurement, process flow, temperature monitoring, dosing, compressed air and utility management."],
  ["Power and Utilities", "Steam, water, compressed air, cooling systems, pressure, temperature and energy related measurements can all form part of plant monitoring and efficiency programmes."],
] as const;

export default function EngineeringPracticePage() {
  return (
    <>
      <PageHero eyebrow="Knowledge Centre" title="Engineering Practice and Industrial Applications" description="Practical guidance on instrument selection, specification, installation, commissioning, verification and industrial applications across the UAE." />
      <main className="py-20 sm:py-28">
        <div className="mx-auto max-w-5xl px-6 lg:px-10">
          <Reveal><Link href="/knowledge-centre" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.18em] text-teal hover:text-ink"><ArrowLeft size={14} /> Back to Knowledge Centre</Link></Reveal>
          <div className="mt-10 space-y-7">
            <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Engineering Practice and Industrial Applications</h2><div className="mt-5 space-y-4 text-sm leading-8 text-mute"><p>Good industrial measurement begins before an instrument is installed.</p><p>The process conditions must first be understood, followed by correct technology selection, specification, installation, commissioning and ongoing verification.</p><p>SensCore approaches instrumentation and industrial solutions around the application. The objective is to understand what needs to be measured, controlled, transferred or protected before selecting the equipment.</p></div></section></Reveal>
            {sections.map(([title, paragraphs]) => <Reveal key={title}><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">{title}</h2><div className="mt-5 space-y-4 text-sm leading-8 text-mute">{paragraphs.map((p) => <p key={p}>{p}</p>)}</div>{title === "Engineering Specification Review" && <div className="mt-7 grid gap-3 sm:grid-cols-2">{specificationPoints.map((item) => <div key={item} className="flex items-start gap-2 rounded-xl border border-line bg-void/30 p-4 text-sm text-mute"><CheckCircle2 className="mt-0.5 shrink-0 text-teal" size={17} />{item}</div>)}</div>}</section></Reveal>)}
            <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Industrial Applications</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{applications.map(([title, text]) => <div key={title} className="rounded-xl border border-line bg-void/30 p-5"><h3 className="font-display text-lg font-semibold text-ink">{title}</h3><p className="mt-2 text-sm leading-7 text-mute">{text}</p></div>)}</div></section></Reveal>
            <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Engineering Support Across the UAE</h2><div className="mt-5 space-y-4 text-sm leading-8 text-mute"><p>Industrial projects in the UAE range from major process facilities to utilities, manufacturing plants, water infrastructure and building services.</p><p>SensCore supports engineering requirements across Abu Dhabi, Dubai, Sharjah, Ajman, Ras Al Khaimah (RAK), Fujairah and Umm Al Quwain (UAQ).</p><p>Our approach considers the application, operating conditions, technical specification and long-term operating requirement before equipment selection.</p><p>Support can include application review, instrument selection, onsite surveys, commissioning, flowmeter verification, compressed air assessments and related industrial engineering requirements.</p></div></section></Reveal>
            <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Frequently Asked Questions</h2><div className="mt-6 space-y-4">{faqs.map(([question, answer], index) => <div key={question} className="rounded-xl border border-line bg-void/30 p-5"><div className="flex items-start gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-teal/30 bg-teal/10 font-mono text-[10px] font-semibold text-teal">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-display text-base font-semibold leading-7 text-ink">{question}</h3><p className="mt-2 text-sm leading-7 text-mute">{answer}</p></div></div></div>)}</div></section></Reveal>
            <Reveal><section className="rounded-2xl border border-line bg-surface p-7 sm:p-9"><h2 className="font-display text-2xl font-semibold text-ink">Need Support with an Industrial Application?</h2><p className="mt-5 text-sm leading-8 text-mute">SensCore can review the application, process conditions and technical requirements to help identify a suitable engineering approach for industrial projects and operating facilities across the UAE.</p><div className="mt-7 flex flex-col gap-4 sm:flex-row"><GlowButton href="/contact">Talk to an Engineer</GlowButton><Link href="/knowledge-centre" className="inline-flex items-center justify-center gap-2 rounded-full border border-line px-6 py-3 text-sm font-medium text-ink transition hover:border-teal/50 hover:text-teal">More Knowledge Centre <ArrowRight size={16} /></Link></div></section></Reveal>
          </div>
        </div>
      </main>
    </>
  );
}
